### ISSUE TITLE
Compatibility with bitsandbytes

### ISSUE THREAD

**Issue by hugoabonizio** [Nuitka/Nuitka#2407]
I'm having some trouble trying to compile a code that uses the [transformers](https://github.com/huggingface/transformers) library with [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) for quantization. Without the flag `load_in_4bit=True`, which uses `bitsandbytes`, everything works fine. But when I enable it I get the error described bellow.

Environment setup:
```
python3 -m venv env1
source env1/bin/activate
python -m pip install nuitka transformers==4.30 bitsandbytes accelerate scipy
python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

Version:
```
1.7.10
Commercial: None
Python: 3.8.10 (default, May 26 2023, 14:05:08) 
Flavor: Debian Python
Executable: /hugo/maritaca/testes/nuitka/test1/env1/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc).
```

Installed packages:
```
accelerate==0.22.0
bitsandbytes==0.41.1
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.25.0
filelock==3.12.2
fsspec==2023.6.0
huggingface-hub==0.16.4
idna==3.4
Jinja2==3.1.2
lit==15.0.7
MarkupSafe==2.1.2
mpmath==1.2.1
networkx==3.0
Nuitka==1.7.10
numpy==1.24.4
ordered-set==4.1.0
packaging==23.1
Pillow==9.3.0
psutil==5.9.5
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
safetensors==0.3.2
scipy==1.10.1
sympy==1.11.1
tokenizers==0.13.3
torch==2.0.1+cu118
torchaudio==2.0.2+cu118
torchvision==0.15.2+cu118
tqdm==4.66.1
transformers==4.30.0
triton==2.0.0
typing-extensions==4.7.1
urllib3==2.0.4
zstandard==0.21.0
```

Script:
```python
from transformers import AutoModelForCausalLM, AutoTokenizer

load_in_4bit = True

model = AutoModelForCausalLM.from_pretrained(
    'facebook/opt-125m',
    load_in_4bit=load_in_4bit,
)
if not load_in_4bit:
	model.to('cuda:0')
tokenizer = AutoTokenizer.from_pretrained('facebook/opt-125m')
tokens = tokenizer('hello', return_tensors='pt').to('cuda:0')

output = model.generate(**tokens, max_new_tokens=5)
print(tokenizer.decode(output[0]))
```

Direct execution:
```
$ python test1.py
</s>hello, I'm a new
```

Building command:
```
python -m nuitka --standalone --include-package=bitsandbytes --include-distribution-metadata=bitsandbytes --include-package=accelerate --include-distribution-metadata=accelerate --output-dir=test1/ test1.py
```

Compiled with `load_in_4bit=False`:
```
$ test1/test1.dist/test1.bin
</s>hello, I'm a new
```

Compiled with `load_in_4bit=True`:
```
$ test1/test1.dist/test1.bin
===================================BUG REPORT===================================                                                                                     
/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run           
                                                                                                                                                                     
python -m bitsandbytes                                                                                                                                               
                                                                                                                                                                     
                                                                                                                                                                     
================================================================================                                                                                     
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}              
/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain [
'libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...                                                                    
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...                                                                  
/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudar
t.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We select the PyTorch default libcudart.
so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<
version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable 
in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr
/local/cuda-11.2                                                                                                                                                     
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}              
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.0.                                                                               
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md             
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118.so. Maybe you need to compile it from source?                                                
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...                                                                                                                  
                                                                                                                                                                     
================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:                                                                                                                 
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md          
2. CUDA driver not installed                                                                                                                                         
3. CUDA not installed                                                                                                                                                
4. You have multiple conflicting CUDA libraries                                                                                                                      
5. Required library not pre-compiled for this bitsandbytes release!                                                                                                  
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):                                                                                                                                   
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/test1.py", line 5, in <module>                                                                           
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/transformers/models/auto/auto_factory.py", line 484, in from_pretrained                                  
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/transformers/modeling_utils.py", line 2685, in from_pretrained                                           
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                  
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                         
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/transformers/utils/bitsandbytes.py", line 11, in <module transformers.utils.bitsandbytes>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/__init__.py", line 6, in <module bitsandbytes>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/research/__init__.py", line 1, in <module bitsandbytes.research>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/research/nn/__init__.py", line 1, in <module bitsandbytes.research.nn>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/research/nn/modules.py", line 8, in <module bitsandbytes.research.nn.modules>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/optim/__init__.py", line 6, in <module bitsandbytes.optim>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/hugo/maritaca/testes/nuitka/test1/test4/test1.dist/bitsandbytes/cextension.py", line 20, in <module bitsandbytes.cextension>
RuntimeError:
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

Am I missing something?

**Comment by carlose2108** [comment]
Hi there!
I got same issue, could you solve this?

**Comment by carlose2108** [comment]
Hi @kayhayen 
Any idea to solve this?

**Comment by kayhayen** [comment]
We need more package configuration for this one likely.

If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

I suspect we might need to make a difference for the package variants they have there, but I am not sure. In other issues, it came up that we include src and include for no good reason, we should check if this case also allows those to be removed.

**Comment by carlose2108** [comment]
Hi @kayhayen 

I tried this but I got same issue.
`- module-name: 'bitsandbytes'
  data-files:
    dirs:
      - 'bitsandbytes-0.41.1-py3.8.egg/bitsandbytes'`
    
First, I ran this command to find the path:
`python -m nuitka --list-package-data=bitsandbytes`

Output:
`venv/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes`

**Comment by kayhayen** [comment]
You are not supposed to put the package directory in data file, they are all automatically from there, it would be hell if we were to encoding random directory names of packages in there. What the tool output is supposed to mean, this is the directory of the package, and what follows are all found data files, and it's not finding one of them, so data files is probably not it.

**Comment by kayhayen** [comment]
I don't know why you think that's a good data files folder, what were you trying to achieve by adding it?

**Comment by kayhayen** [comment]
The bitsandbytes issue is solved in 4.0 already I believe, definitely with what I have internally for 4.1, the issue is stale.
