### ISSUE TITLE
Standalone compilation with CuPy fails to detect GPU (cupy.is_available() is False)

### ISSUE THREAD

**Issue by zelenooki87** [Nuitka/Nuitka#3507]
Hello Nuitka Team,
First of all, thank you for your incredible work on Nuitka. It's a fantastic tool.
I'm facing an issue with creating a standalone executable for a Windows application that uses CuPy for GPU acceleration. While the compiled application runs without crashing, it fails to detect the GPU, and cupy.is_available() returns False. The application then falls back to CPU processing as expected, but the goal is to enable GPU support.
I've tried numerous approaches, including manually including all necessary CUDA and MKL DLLs, but the issue persists.
System and Software Information:
•	Nuitka Version: 2.7.6 (Commercial: not installed)
•	Python Version: 3.12.11 (Anaconda)
•	OS: Windows 11
•	CuPy Installation Method: conda install -c conda-forge cupy (Version: 13.4.1)
•	CUDA Toolkit Version (System-wide): 12.9
•	GPU: NVIDIA RTX 3090
•	NVIDIA Driver Version: 576.40
Problem Description:
The core of the problem is that the try...except block for importing CuPy fails in the compiled version, even though all dependencies seem to be present in the distribution folder.
This is the code snippet used to check for GPU availability:
      # At the start of the main script (GUI.py)
import sys
import os

# When frozen, add the application's directory to the DLL search path
if getattr(sys, 'frozen', False) and sys.platform.startswith('win'):
    application_path = os.path.dirname(sys.executable)
    try:
        os.add_dll_directory(application_path)
    except AttributeError:
        os.environ['PATH'] = application_path + os.pathsep + os.environ.get('PATH', '')

# Attempt to import CuPy
try:
    import cupy as cp
    GPU_AVAILABLE = cp.is_available()
except ImportError:
    GPU_AVAILABLE = False

# In the compiled app, GPU_AVAILABLE is always False.
    
Nuitka Command Used:
This is the final command I've used, which includes all MKL DLLs from the Conda environment and the core CUDA runtime DLLs from the system-wide CUDA Toolkit installation.
      python -m nuitka ^
   --standalone ^
   --output-filename=PhotoAutoCorrection.exe ^
   --output-dir=build ^
   --windows-console-mode=attach ^
   --enable-plugin=pyside6 ^
   --noinclude-pytest-mode=nofollow ^
   --noinclude-setuptools-mode=nofollow ^
   --include-package=cupy ^
   --include-package=skimage ^
   --include-package=pyexiv2 ^
   --include-package=rawpy ^
   --include-package=pillow_heif ^
   --include-package=tifffile ^
   --include-package=scipy.interpolate ^
   --include-package=scipy.ndimage ^
   --include-package=scipy.signal ^
   --include-package=scipy.optimize ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/mkl_core.2.dll=mkl_core.2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/mkl_intel_thread.2.dll=mkl_intel_thread.2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/mkl_sequential.2.dll=mkl_sequential.2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/libiomp5md.dll=libiomp5md.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/mkl_def.2.dll=mkl_def.2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/mkl_avx2.2.dll=mkl_avx2.2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/mkl_avx512.2.dll=mkl_avx512.2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/mkl_rt.2.dll=mkl_rt.2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Lib/site-packages/pyexiv2/lib/exiv2.dll=pyexiv2/lib/exiv2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/raw_r.dll=raw_r.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/lcms2.dll=lcms2.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/libtiff.dll=libtiff.dll" ^
   --include-data-files="C:/Users/admin/anaconda3/envs/aplikacija/Library/bin/zlib.dll=zlib.dll" ^
   --include-data-files="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.9/bin/cudart64_12.dll=cudart64_12.dll" ^
   --include-data-files="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.9/bin/nvrtc-builtins64_129.dll=nvrtc-builtins64_129.dll" ^
   App/GUI.py
    
What I've tried:
1.	Initially, the app crashed due to missing MKL DLLs. This was resolved by explicitly including them.
2.	Then, I noticed CuPy was not working. I identified that cudart64_12.dll was missing from the distribution.
3.	I manually added cudart64_12.dll and nvrtc-builtins64_129.dll to the Nuitka command. The files are now present in the final build directory.
4.	I added the os.add_dll_directory() logic at the very start of my script to ensure the application's directory is in the DLL search path.
Despite all these steps, the import cupy statement still seems to fail silently or cupy.is_available() returns False. The application does not crash, it just reports no GPU support.
Could there be another dependency I'm missing, or is there a specific Nuitka plugin or option required for the latest versions of CuPy? Any guidance would be greatly appreciated.
Thank you for your time and help!

**Comment by Kevin-O-Hsu** [comment]
Please let us know what's the real problem? Cannot import cupy or cupy.is_available() returns False?
Debug first please

**Comment by zelenooki87** [comment]
@Kevin-O-Hsu 
The core issue I'm facing is getting Nuitka to correctly bundle the CuPy library for hardware acceleration with Nvidia GPUs. The objective is to create a standalone application that contains all required libraries, with a graceful fallback to NumPy on the CPU for systems that lack an Nvidia GPU.

I have already tried all possible configurations. I initially suspected a CUDA version mismatch—my CuPy was compiled for CUDA 12.8, while my system has 12.9. However, even after installing the older CUDA toolkit to match it, the problem persists.

Essentially, gui.py is the main script that runs the PySide6 interface. I am able to successfully build the application, but it's missing the CuPy acceleration.

My question is: do I need to specify within the gui.py script itself which files Nuitka should include and "freeze" for the compilation?

Could you provide the correct Nuitka command needed to compile an application with the following dependencies ?


`conda list
# packages in environment at C:\Users\ \anaconda3\envs\aplikacija:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2025.4.26            h4c7d964_0    conda-forge
cffi                      1.17.1                   pypi_0    pypi
cryptography              45.0.4                   pypi_0    pypi
cuda-cccl_win-64          12.9.27              h57928b3_0    conda-forge
cuda-cudart-dev_win-64    12.9.79              he0c23c2_0    conda-forge
cuda-cudart-static_win-64 12.9.79              he0c23c2_0    conda-forge
cuda-cudart_win-64        12.9.79              he0c23c2_0    conda-forge
cuda-nvrtc                12.9.86              he0c23c2_0    conda-forge
cuda-version              12.9                 h4f385c5_3    conda-forge
cupy                      13.4.1          py312h4669ff0_1    conda-forge
cupy-core                 13.4.1          py312hf032bbf_1    conda-forge
fastrlock                 0.8.3           py312h4023b64_1    conda-forge
freeglut                  3.2.2                he0c23c2_3    conda-forge
imageio                   2.37.0                   pypi_0    pypi
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
jasper                    4.2.5                h99a1cce_0    conda-forge
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.17                 hbcf6048_0    conda-forge
lerc                      4.0.0                h6470a55_1    conda-forge
libblas                   3.9.0           31_h641d27c_mkl    conda-forge
libcblas                  3.9.0           31_h5e41251_mkl    conda-forge
libcublas                 12.9.1.4             he0c23c2_0    conda-forge
libcufft                  11.4.1.4             he0c23c2_0    conda-forge
libcurand                 10.3.10.19           he0c23c2_0    conda-forge
libcusolver               11.7.5.82            he0c23c2_0    conda-forge
libcusparse               12.5.10.65           he0c23c2_0    conda-forge
libdeflate                1.24                 h76ddb4d_0    conda-forge
libexpat                  2.7.0                he0c23c2_0    conda-forge
libffi                    3.4.6                h537db12_1    conda-forge
libhwloc                  2.11.2          default_ha69328c_1001    conda-forge
libiconv                  1.18                 h135ad9c_1    conda-forge
libjpeg-turbo             3.1.0                h2466b09_0    conda-forge
liblapack                 3.9.0           31_h1aa476e_mkl    conda-forge
liblzma                   5.8.1                h2466b09_2    conda-forge
libnvjitlink              12.9.86              he0c23c2_0    conda-forge
libraw                    0.21.4               h866491b_0    conda-forge
libsqlite                 3.50.1               h67fdade_0    conda-forge
libtiff                   4.7.0                h05922d8_5    conda-forge
libwinpthread             12.0.0.r4.gg4f2fc60ca      h57928b3_9    conda-forge
libxml2                   2.13.8               h442d1da_0    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
mkl                       2024.2.2            h66d3029_15    conda-forge
networkx                  3.5                      pypi_0    pypi
nuitka                    2.7.7                    pypi_0    pypi
numpy                     2.3.0                    pypi_0    pypi
opencv-python             4.11.0.86                pypi_0    pypi
openssl                   3.5.0                ha4e3fda_1    conda-forge
ordered-set               4.1.0                    pypi_0    pypi
packaging                 25.0                     pypi_0    pypi
pillow                    11.2.1                   pypi_0    pypi
pillow-heif               0.22.0                   pypi_0    pypi
pip                       25.1.1             pyh8b19718_0    conda-forge
psutil                    7.0.0                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pyexiv2                   2.15.4                   pypi_0    pypi
pyside6                   6.9.1                    pypi_0    pypi
pyside6-addons            6.9.1                    pypi_0    pypi
pyside6-essentials        6.9.1                    pypi_0    pypi
python                    3.12.11         h3f84c4b_0_cpython    conda-forge
python_abi                3.12                    7_cp312    conda-forge
rawpy                     0.25.0                   pypi_0    pypi
scikit-image              0.25.2                   pypi_0    pypi
scipy                     1.15.3                   pypi_0    pypi
setuptools                80.9.0             pyhff2d567_0    conda-forge
shiboken6                 6.9.1                    pypi_0    pypi
tbb                       2021.13.0            h62715c5_1    conda-forge
tifffile                  2025.6.1                 pypi_0    pypi
tk                        8.6.13               h2c6b04d_2    conda-forge
tzdata                    2025b                h78e105d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
vc                        14.3                h2b53caa_26    conda-forge
vc14_runtime              14.42.34438         hfd919c2_26    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
zstandard                 0.23.0                   pypi_0    pypi
zstd                      1.5.7                hbeecb71_2    conda-forge`




Thank you very much for your help. I am new to the Nuitka compiler, so I apologize if this turns out to be a trivial issue.
